# Generated by Django 4.2.16 on 2025-03-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_text", models.TextField()),
                ("unbiased_text", models.TextField()),
                ("rewritten_text", models.TextField()),
                ("bias_score", models.FloatField()),
            ],
        ),
    ]
