# Generated by Django 4.2.16 on 2025-03-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_newsanalysis_bias_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsanalysis",
            old_name="unbiased_text",
            new_name="rewritten_text",
        ),
        migrations.AddField(
            model_name="newsanalysis",
            name="bias_score",
            field=models.FloatField(default=50.0),
        ),
    ]
